* em

~em~ is a small Python wrapper script for =emacsclient=, serving
the following needs:

 - =emacsclient='s arguments are kinda wacky, at least to me
 - Takes care of launching a server if one doesn't exist
 - If you have a bloated =.emacs.d= like I do, show an animated
   GIF while you wait for Emacs to start

* Dependencies

 - Python 3.6+
 - Tkinter (may need to install from distro repos)
 - [[https://github.com/pipxproject/pipx][pipx]]

Once you have pipx installed, installing this script should just be a
simple matter of

#+begin_src shell
  pipx install 'git+https://github.com/jws85/em.git'
#+end_src

which should pull in ~em~ into its own virtualenv but still leave it
accessible from the command line.  Removing ~em~ is just as easy:

#+begin_src shell
  pipx uninstall em
#+end_src

* Usage

=em= fires up a new Emacs GUI frame.

=em file.txt= does the same, but viewing =file.txt=.

=em -t= loads a new Emacs terminal frame, etc.

=em -l '(some-lisp-here)'= runs arbitrary elisp.

=em -h= prints help.

* Customization

Have your own loading gif?  Create the file =$HOME/.config/em/em.conf=
and put something like:

#+begin_src conf
  [DEFAULT]
  LoadingGif = ~/Pictures/my-kewl-loading.gif
#+end_src

and it'll load your gif rather than the one I've included.

* Credits

The loading icon comes from [[https://www.reddit.com/r/loadingicon/comments/6hy8cd/when_loading_takes_forever_oc/][this Reddit thread]], which seems to be the
original source as far as I can tell?  So, the creator appears to be
[[https://www.reddit.com/user/PortablePawnShop][/u/PortablePawnShop]].
